config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root 'items#index'
  
  resources :items  
  resources :carts
  resources :order_items, only: [:create, :update, :destroy]
  
  post '/items/:id', to: 'items#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :cart, optional: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_one :cart

  def display_name
    "#{self.first_name} #{self.last_name}"
  end


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    
  end

  def show
  end

 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show,  :update]
  
  def index
    @items = Item.where(cart_id: nil)
    if !current_user.cart
      Cart.create(user_id: current_user.id)
    end
  end

  def create
    old_item = Item.find(params[:format])
    @item = current_user.cart.items.new(name: old_item.name, price: old_item.price, photo: old_item.photo, cart_id: current_user.cart.id)
    @item.save
    redirect_to cart_path(current_user)
  end

  def show
    
  end

 def destroy
  @item.find(params[:format])
  @item.destroy
  redirect_to cart_path(current_user)
 end
  
  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @user = User.find(params[:id])
  end


  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_shopping.html.erb
<% if current_user.cart.items.any?  %>
  <% current_user.cart.items.each do |item|%>
  <div class="sixteen wide mobile eight wide tablet four wide computer column">
    <div class='ui cards'>
      <div class= 'card'>
        <div class="image">
          <img src="https://robohash.org/<%= item.photo %>?set=4" />
        </div>
        <div class='content'>
        <%= item.name %>
        </div>
  <%= link_to 'add more items', items_path, class: 'ui button' %>
  <%= link_to 'remove item', item_path, method: :delete, class: 'ui button'%>
      </div>
    </div>
    </div>
  <% end %>
  <% else %>
    <p> There are no items in your shopping cart. Please add items to your cart. </p>
  <% end %>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<div class='background'>
  <div class="ui header center aligned">
    <h1 class="box">Thank you for your order! You're awesome!</h1>
  </div>
</div>

app/views/carts/show.html.erb
<div class='ui container'>
<h1>Shopping Cart</h1>
<h2> </h2>

<div class="ui grid">
 <%= render "shopping" %>
</div>

 <br />
  <%= link_to 'checkout', carts_path, class: 'ui button' %>

</div>

app/views/items/index.html.erb
<div class='ui container'>
<div class="ui four column centered grid">
  <div class="row" style="background-color: lightblue;color: black; margin-top: 2%">
     <div class="column">
       <div class="ui header center aligned">
         <h1>Welcome to RoboStore!</h1></div>
         <div class="ui header center aligned">
      <h3>For everything robot! </h3></div>
    </div>
  </div>
  <br />
</div>
<div class="ui divider"></div>
<div class="ui grid">
    <% @items.each do |item| %>
      <div class="sixteen wide mobile eight wide tablet four wide computer column">
       <div class="ui card">
        <div class="image">
            <img src="https://robohash.org/<%= item.photo %>?set=4" />
          </div>
          <div class="content">
            <h1 class="header center aligned">
              <%= link_to item.name, item_path(item) %>
            </h1>
          </div>
            <p class="center aligned">$<%= item.price %></p>
          <div class='ui bottom attached button'>
             <i class="add icon"></i>
            <%= link_to 'View Item', item_path(item) %>
          </div>
         </div>
      </div>
    <% end %>
</div>


<div class="ui divider"></div>
<div class="ui equal width center aligned padded grid">
  <div class="row">
    <div class="black column"> </div>
    <div class="blue column"> </div>
  </div>
<br />
</div>
<<<<<<< HEAD
<div class="ui divider"></div>





=======
</div>
>>>>>>> final changes

app/views/items/show.html.erb
<div class="ui row" style="background-color: lightgrey;color: black;">
   <div class="column">
    <div class="ui header center aligned aligned">
      <h1 class="centered">You are viewing... <%= @item.name %></h1>
      </div>
   </div>
</div>
<div class="ui divider"></div>
<div class="ui centered grid">
  <div class="sixteen wide mobile eight wide tablet four wide computer column">
    <div class="ui centered yellow card">
      <div class="image">
        <img src="https://robohash.org/<%= @item.photo %>?set=4" />
      </div>
        <div class="content">
          <a class="header center aligned">
            $<%= @item.price %>
          </a>
        </div>
          <div class="description">
            <p class="center aligned">Adopt me today!</p>
          </div>
            <div class="extra content">
              <div class="ui two buttons">
                <div class="ui green button">
                <i class="add to cart icon"></i>
                <%= link_to 'Add', items_path(@item), method: :post %>
                </div>
                <div class="or"></div>
                <div class="ui button">
                <%= link_to 'Back', items_path %>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

<div class="ui divider"></div>
<div class="ui equal width center aligned padded grid">
  <div class="row">
    <div class="blue column"> </div>
    <div class="blue column"> </div>
  </div>
<br />
</div>
<div class="ui divider"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <div class="ui top menu">
      <% unless user_signed_in? %>
      <% else %>  
         <%= link_to "Home", root_path, class: "active blue item" %>
        <%= link_to 'View Cart', cart_path(current_user), class:'item'%>
        <%= link_to 'View Account', user_path(current_user), class: 'item' %>
      <% end %>  
      <div class="right menu">
        <% unless user_signed_in? %>
          <%= link_to new_user_registration_path, class: "item" do%>
          <i class="signup icon blue"></i> Sign Up
          <% end %>
          <%= link_to new_user_session_path, class: "item" do %>
          <i class="sign in icon teal"></i> Login
          <% end %>
        <% else %>
          <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"}, class: "item" do %>
          <i class="sign out icon red"></i> Logout
        <% end %>

        <% end %>
      </div>
    </div>

     <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
    <%= yield %>
  
  </body>
</html>




        

app/views/users/show.html.erb
<div class='ui container'>
<h1>Your Account Information!</h1>
<hr />

</br>

<table class="ui very basic table">
  <thead>
    <tr>
      <th><font size="4">First Name</th>
      <th><font size="4">Last Name</th>
      <th><font size="4">Email Address</th>
      <th><font size="4">Member since:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><font size="3"><%= @user.first_name %></td>
      <td><font size="3"><%= @user.last_name %></td>
      <td><font size="3"><%= @user.email %></td>
      <td><font size="3"><%= @user.created_at %></td>
    </tr>
</table>

</br>

<%= link_to 'Home', items_path, class: 'ui button' %>
<%= link_to 'Edit Account', edit_user_registration_path, class: 'ui button' %>